# Etapa Base
FROM node:20-slim AS base
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile && yarn cache clean
COPY . .

# Etapa de Desenvolvimento
FROM base AS development
CMD ["yarn", "run", "start"]

# Etapa de Build (compila o código TypeScript para JavaScript)
FROM base AS build
RUN yarn build

# Etapa de Produção
FROM node:20-slim AS production
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile
CMD ["node", "dist/main.js"]