apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacka-video-service-deployment
  labels:
    app: hacka-video-service-app
spec:
  replicas: 1  # Número de réplicas/pods que serão criadas
  selector:
    matchLabels:
      app: hacka-video-service-app
  template:
    metadata:
      labels:
        app: hacka-video-service-app
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: apis-node-group
      containers:
      - name: hacka-video-service-app
        image: luizpainodev/hacka-video-service:latest
        envFrom:
        - configMapRef:
            name: hacka-video-service-config-map
        - secretRef:
            name: hacka-video-service-secrets
        ports:
        - containerPort: 3001  # Porta em que sua aplicação escuta
